# Generated by Django 5.2.6 on 2025-12-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_comment_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='comments_media/'),
        ),
        migrations.AddField(
            model_name='task',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='tasks_media/'),
        ),
    ]
